language: python
python:
  - "2.7"
install:
  - "pip install -r requirements.txt --use-mirrors"
  - "pip install pytest pytest-cov pytest-pep8"
  - "pip install coverage"
  - "pip install coveralls"
script:
  - "py.test aospy_synthetic  --cov=aospy_synthetic --cov-report term-missing"
after_success:
  - coveralls
  